stages:
  - test
  - build

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHORT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHORT_SHA"

vet:
  stage: test
  image: golang:1.13
  script:
    - go vet -v ./...

lint:
  stage: test
  image: golang:1.13
  before_script:
    - go get -u golang.org/x/lint/golint
  script:
    - golint -set_exit_status ./...
