stages:
  - test
  - build

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE || true
  script:
    - docker build --cache-from $CI_REGISTRY_IMAGE --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" .
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master

vet:
  stage: test
  image: golang:1.13
  script:
    - go vet -v ./...

#lint:
#  stage: test
#  image: golang:1.13
#  before_script:
#    - go get -u golang.org/x/lint/golint
#  script:
#    - golint -set_exit_status ./...
